name: check-service-labels

permissions:
  pull-requests: read
  checks: write

on:
  pull_request:
    types: [opened, edited, reopened, labeled, unlabeled, synchronize]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    if: "${{ contains(github.event.pull_request.labels.*.name, 'Servicing-approved') }}"
    steps:
    - name: Pass with 'Servicing-approved' label
      run: exit 0
